### PR TITLE
Fixed some issues around ReferenceCodec in OpenAPI spec rendering

### PR DESCRIPTION
**Pull request by daniel-chambers**
There is a currently an issue where [`declareSchemaRef`](https://www.stackage.org/haddock/lts-18.22/openapi3-3.1.0/src/Data.OpenApi.Internal.Schema.html#declareSchemaRef) from the `openapi3` package interferes with the way that `ReferenceCodec` controls its recursion to prevent infinite loops. What ends up happening is that `declareSchemaRef` preregisters the named schema into the `Declare` monad to prevent infinite loops, which is the same technique that `ReferenceCodec` uses, which results in `ReferenceCodec` not running fully and declaring all the necessary dependent schemas. `declareSchemaRef` is used by servant when generating OpenAPI specs, so that's how I ran into this issue.

I solved this problem by tracking the recursion state of `declareNamedSchemaVia` in a separate State monad instead of doing it in the Declare monad. This way it does not conflict with `declareSchemaRef`.

I've added a `MutuallyRecursiveA` test case and set of golden tests that use `declareSchemaRef` that demonstrate the problem (`autodocodec-api-usage/test_resources/openapi-schema/declareSchemaRef/mutually-recursive.json`). 

The PR also fixes an issue where the `NamedSchema` returned when processing `ReferenceCodec` was not renamed with the name specified. This resulted in unnecessary duplicate schemas getting added to the final OpenAPI spec. You can see this particular issue by looking at the old golden test result for the `Recursive` type (`autodocodec-api-usage/test_resources/openapi-schema/recursive.json`), which has a duplicate spec in there.

I also adjusted the `LegacyValue` test case (`autodocodec-api-usage/test_resources/openapi-schema/legacy-value.json`) because both the "new" and "old" objects were given the same name, which resulted in the final schema missing the actual definition of the old object schema. By giving the old object a different name, the OpenAPI schema now correctly contains both the old and new schemas.

I've added the tests commit before the fixes, so if you check out that commit you can see how the existing code fails.

### CODE REVIEW

**Comment by NorfairKing** [comment]
This looks like a perfect PR, but CI is derping out. Let me see if I can get it to run.

**Comment by NorfairKing** [comment]
You'll need this diff to make CI happy about formatting:
https://pastebin.com/vLhwbGvm
And this diff to make `--pedantic` happy:
https://pastebin.com/eGXtQZKR

**Comment by daniel-chambers** [comment]
@NorfairKing Thanks for those patches, I've applied them 🙂

**Comment by daniel-chambers** [comment]
@NorfairKing Is there something more I can do to help get this PR merged? 🙂

**Comment by NorfairKing** [comment]
Oh dear @daniel-chambers I'm sorry I missed this. Thanks for the extra ping. Let me get this merged today.

**Comment by NorfairKing** [comment]
@daniel-chambers I can merge as-is but then I cannot release to hackage.
Any chance you could do the version bumps and changelog updates?
I think your changelog description would be more accurate than what I could write.

**Comment by daniel-chambers** [comment]
@NorfairKing No problem! I've given it a major version bump because all the functions in `Autodocodec.OpenAPI.Schema` are exported by default and I changed the type signature of two top level functions in there. It does feel like the two functions I changed probably shouldn't be exported though, they look like utility functions for the module internals to me...

Hopefully the changelog notes are okay! It's a bit hard to be concise and still describe the changes well, unfortunately. 😀

**Comment by daniel-chambers** [comment]
Unless you want to release #15 as a whole separate version, perhaps we could merge this PR, update the changelog in that PR and then release both together as 0.2.0.0? (The author of #15 is my colleague and we'd like both changes released if possible 🙂)

**Comment by NorfairKing** [comment]
@daniel-chambers Excellent. Merging both now.

**Pull request closed without merging**
