### PR TITLE
Disjoint codecs

### PR DESCRIPTION
**Pull request by dmoverton**
Add disjoint versions of the various "choice" codec combinators: `matchChoiceCodec`, `matchChoicesCodec`, `enumCodec`, `stringConstCodec`, and `shownBoundedEnumCodec`.

### CODE REVIEW

**Review by NorfairKing — APPROVED** [review]
Happy to merge as-is but would like to see docs with examples and an explanation about when you use which.

**Comment by dmoverton** [comment]
> Happy to merge as-is but would like to see docs with examples and an explanation about when you use which.

Thanks. I'm not really sure when you'd want to use `PossiblyJointUnion` (i.e. `anyOf`) to be honest. At least for what we're doing only `DisjointUnion` (`oneOf`) makes sense.

E.g. for enums I think you need to be disjoint. For sums of object types you maybe want `anyOf` to model some weird Javascript types, but I don't think it's really useful for Haskell sum types. Also, the `FromJSON` and `ToJSON` instances that `Autodocodec` generates don't really provide the expected behaviour of `anyOf` anyway. `FromJSON` just takes the first alternative that matches and throws away any other object properties.

I thought about just changing `matchChoiceCodec`, etc to be disjoint, but I didn't want to in case it broke someone else's use case.  What do you think?

**Comment by NorfairKing** [comment]
@dmoverton I don't want to keep you waiting. I'm happy to break backwards compatibility if what we're fixing is a bug. How do you propose we proceed?

**Comment by dmoverton** [comment]
I'm on vacation and won't be able to respond properly until Monday. I'd suggest adding disjoint versions of `matchChoiceCodec` and `matchChoicesCodec`, and implementing the other functions using those. If you think that's a reasonable solution then I'll implement it next week.

**Comment by NorfairKing** [comment]
Sounds great. Let's make sure this is tested and documented so that we can have the tests tell us if it's a good idea.

**Comment by NorfairKing** [comment]
@dmoverton gentle ping

**Comment by dmoverton** [comment]
> @dmoverton gentle ping

Sorry I haven't had a chance to get back to this yet. I'll try to do it by the end of the week.

**Comment by NorfairKing** [comment]
@dmoverton It looks like this is ready. What do you think?

**Comment by dmoverton** [comment]
> @dmoverton It looks like this is ready. What do you think?

I'm happy with it if you are.

**Comment by NorfairKing** [comment]
@dmoverton I added some more docs and exports, and made sure that CI can fail if the golden tests are wrong.
Please have a quick look at the `disjoint` branch to see if these are ok for you, then I'll merge and release today.

**Comment by dmoverton** [comment]
> @dmoverton I added some more docs and exports, and made sure that CI can fail if the golden tests are wrong. Please have a quick look at the `disjoint` branch to see if these are ok for you, then I'll merge and release today. In particular, see [4f4b23d](https://github.com/NorfairKing/autodocodec/commit/4f4b23d7505f676ee3e4bc9ec31754904f45d744) and [c08af9f](https://github.com/NorfairKing/autodocodec/commit/c08af9fa8de45400d42bf6f6bcd564b865c8b9b1)

Thanks. Looks good to me.

**Comment by NorfairKing** [comment]
@dmoverton Thanks to this PR, I was able to make this little change that i've been wanting to make: 38bd486

**Pull request merged**
