### PR TITLE
Add a Profunctor instance to Codec

### PR DESCRIPTION
**Pull request by clintonmead**
Not much to say. Codecs are Profunctors. Might as well implement the interface. 

Shout out if you need anything else in this PR.

### CODE REVIEW

**Comment by NorfairKing** [comment]
> Not much to say. Codecs are Profunctors. Might as well implement the interface.

No. Implement as few instances as possible.
Never implement instances that you don't use by using generic functions.
In particular, `profunctor` has an ENORMOUS dependency footprint

**Comment by clintonmead** [comment]
Would you be okay with a PR to add the following constructor to `Codec`?

```
type data RequiredOptionalPairTag

RequiredOptionalPair ::
  ObjectCodec (Maybe input) (Maybe output) ->
  ObjectCodec input output ->
  Codec RequiredOptionalPairTag input output
```

The alternative is defining this outside of autodocodoc:

```
data RequiredOptionalCodecPair context a b = RequiredOptionalFieldCodec
  { requiredFieldCodec :: Codec context a b
  , optionalFieldCodec :: Codec context (Maybe a) (Maybe b)
  }
```

But then to avoid having copy/pasta functions on codec pairs and ordinary `Codec`s, I need to define Profunctor and SumProfunctor instances for `Codec`.

But I could add such a datatype to the `Codec` directly. Alternatively I could just define Profunctor/SumProfunctor orphans for `Codec`. 

In a way adding the constructor gives more power, as for example, the choice of `SumProfunctor` is non-obvious (is it `eitherCodec` or `disjointEitherCodec`. Adding the constructor allows one to be more specific, if you're happy to have the extra constructor.

**Comment by NorfairKing** [comment]
@clintonmead Can you elaborate on the use of the `RequiredOptionalPair`? I think you probably have a real use-case here but I don't see it yet and I'd like to understand.

**Comment by clintonmead** [comment]
@NorfairKing  The real use case is somewhat obscured by the fact that someone is paying me to develop closed source software so I can't just throw you real life examples.

But roughly speaking what I'm doing is defining our types in a form like the following:

```
data Blah f = Blah
  { var1 :: f (MyLib.Identifier BlahType)
  , var2 :: f (MyLib.Readonly Blah2Type)
  , var3 :: f (MyLib.Overwritable Blah3Type)
  }
```

And we can substitute in various values of `f`, and get different autodocodcec serialisers/deseriaisers.

When `f` is `Value`, we just get all the values.

When `f` is `Key` we get a serialiser that just expects the key value.

When `f` is `Overwrite`,  we get a serialiser that expects an identifier `var1` and a overwritable field `var3`, but not `var2` because that is readonly.

The whole point of me doing this is to combine it with servant and opaleye to autogen GET/POST/PATCH endpoints without actually having to write any implementation code, just define you're datatype, and you've got a bunch of endpoints with OpenApi descriptors that appropriately modify your postgres database. 

But when building these, for example, the PATCH endpoint has all it's keys as optional. An empty PATCH is valid. But the POST endpoint, requires all these keys to have values.

I think that coupling the optional and required keys makes it easier define these endpoints. That way, I can just define a codec once, and then specialising it late for "required" or "optional". Then I can use the same logic for POST and PATCH, the only difference is a type specialisation at the end. 

I think what I'll do is do a PR myself, make sure it actually works with idea I'm trying to achieve, then throw a PR to you. I actually think adding an extra constructor is the best solution, it's just somewhat disruptive, but GHC will help me fix everything, and I don't think there's many dependencies on Autodocodec's internals yet yes?

**Comment by clintonmead** [comment]
Yeah scrap this idea of the extra constructor I can't implement `parseJSONContextVia` sensibly for it.

**Comment by clintonmead** [comment]
Scrap the above, I'm thinking a different direction now. I'll get back to you when I've got something concrete.

**Pull request closed without merging**
