### PR TITLE
Add a type field when generating enum schema from EqCodec

### PR DESCRIPTION
**Pull request by dmoverton**
This PR adds a `type` field for enum values when generating an OpenAPI schema from `EqCodec`.
This is required to work around an [issue with `swagger-ui`](https://github.com/swagger-api/swagger-ui/issues/6906) where it does not show the enum value unless a type is also given.

### CODE REVIEW

**Comment by NorfairKing** [comment]
Oeh that's really smart! Let's see what CI says.

**Comment by NorfairKing** [comment]
Wouldn't mind a changelog here either, but let me merge #16 first.

**Comment by dmoverton** [comment]
I added a changelog entry. I put it under 0.2.0.0, assuming you want to release this along with #16. Please feel free to move it if that's not your plan.

**Comment by NorfairKing** [comment]
Merged and released!

**Pull request merged**
